// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateRoleMethodNotAllowedCode is the HTTP code returned for type CreateRoleMethodNotAllowed
const CreateRoleMethodNotAllowedCode int = 405

/*CreateRoleMethodNotAllowed Invalid input

swagger:response createRoleMethodNotAllowed
*/
type CreateRoleMethodNotAllowed struct {
}

// NewCreateRoleMethodNotAllowed creates CreateRoleMethodNotAllowed with default headers values
func NewCreateRoleMethodNotAllowed() *CreateRoleMethodNotAllowed {

	return &CreateRoleMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateRoleMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// CreateRoleInternalServerErrorCode is the HTTP code returned for type CreateRoleInternalServerError
const CreateRoleInternalServerErrorCode int = 500

/*CreateRoleInternalServerError Internal Server Error

swagger:response createRoleInternalServerError
*/
type CreateRoleInternalServerError struct {
}

// NewCreateRoleInternalServerError creates CreateRoleInternalServerError with default headers values
func NewCreateRoleInternalServerError() *CreateRoleInternalServerError {

	return &CreateRoleInternalServerError{}
}

// WriteResponse to the client
func (o *CreateRoleInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
