// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeleteRoleByIDHandlerFunc turns a function with the right signature into a delete role by Id handler
type DeleteRoleByIDHandlerFunc func(DeleteRoleByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteRoleByIDHandlerFunc) Handle(params DeleteRoleByIDParams) middleware.Responder {
	return fn(params)
}

// DeleteRoleByIDHandler interface for that can handle valid delete role by Id params
type DeleteRoleByIDHandler interface {
	Handle(DeleteRoleByIDParams) middleware.Responder
}

// NewDeleteRoleByID creates a new http.Handler for the delete role by Id operation
func NewDeleteRoleByID(ctx *middleware.Context, handler DeleteRoleByIDHandler) *DeleteRoleByID {
	return &DeleteRoleByID{Context: ctx, Handler: handler}
}

/*DeleteRoleByID swagger:route DELETE /roles/{id} Roles deleteRoleById

Delete role by ID

Deletes a single role

*/
type DeleteRoleByID struct {
	Context *middleware.Context
	Handler DeleteRoleByIDHandler
}

func (o *DeleteRoleByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeleteRoleByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
