// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllRolesHandlerFunc turns a function with the right signature into a get all roles handler
type GetAllRolesHandlerFunc func(GetAllRolesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllRolesHandlerFunc) Handle(params GetAllRolesParams) middleware.Responder {
	return fn(params)
}

// GetAllRolesHandler interface for that can handle valid get all roles params
type GetAllRolesHandler interface {
	Handle(GetAllRolesParams) middleware.Responder
}

// NewGetAllRoles creates a new http.Handler for the get all roles operation
func NewGetAllRoles(ctx *middleware.Context, handler GetAllRolesHandler) *GetAllRoles {
	return &GetAllRoles{Context: ctx, Handler: handler}
}

/*GetAllRoles swagger:route GET /roles Roles getAllRoles

Get All roles

*/
type GetAllRoles struct {
	Context *middleware.Context
	Handler GetAllRolesHandler
}

func (o *GetAllRoles) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllRolesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
