// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "models"
)

// GetRoleByIDOKCode is the HTTP code returned for type GetRoleByIDOK
const GetRoleByIDOKCode int = 200

/*GetRoleByIDOK successful operation

swagger:response getRoleByIdOK
*/
type GetRoleByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Role `json:"body,omitempty"`
}

// NewGetRoleByIDOK creates GetRoleByIDOK with default headers values
func NewGetRoleByIDOK() *GetRoleByIDOK {

	return &GetRoleByIDOK{}
}

// WithPayload adds the payload to the get role by Id o k response
func (o *GetRoleByIDOK) WithPayload(payload *models.Role) *GetRoleByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get role by Id o k response
func (o *GetRoleByIDOK) SetPayload(payload *models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRoleByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRoleByIDBadRequestCode is the HTTP code returned for type GetRoleByIDBadRequest
const GetRoleByIDBadRequestCode int = 400

/*GetRoleByIDBadRequest Invalid ID supplied

swagger:response getRoleByIdBadRequest
*/
type GetRoleByIDBadRequest struct {
}

// NewGetRoleByIDBadRequest creates GetRoleByIDBadRequest with default headers values
func NewGetRoleByIDBadRequest() *GetRoleByIDBadRequest {

	return &GetRoleByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetRoleByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetRoleByIDNotFoundCode is the HTTP code returned for type GetRoleByIDNotFound
const GetRoleByIDNotFoundCode int = 404

/*GetRoleByIDNotFound Role not found

swagger:response getRoleByIdNotFound
*/
type GetRoleByIDNotFound struct {
}

// NewGetRoleByIDNotFound creates GetRoleByIDNotFound with default headers values
func NewGetRoleByIDNotFound() *GetRoleByIDNotFound {

	return &GetRoleByIDNotFound{}
}

// WriteResponse to the client
func (o *GetRoleByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
