// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteUserByIDReader is a Reader for the DeleteUserByID structure.
type DeleteUserByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteUserByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteUserByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteUserByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteUserByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteUserByIDOK creates a DeleteUserByIDOK with default headers values
func NewDeleteUserByIDOK() *DeleteUserByIDOK {
	return &DeleteUserByIDOK{}
}

/*DeleteUserByIDOK handles this case with default header values.

successful operation
*/
type DeleteUserByIDOK struct {
}

func (o *DeleteUserByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUserByIdOK ", 200)
}

func (o *DeleteUserByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserByIDBadRequest creates a DeleteUserByIDBadRequest with default headers values
func NewDeleteUserByIDBadRequest() *DeleteUserByIDBadRequest {
	return &DeleteUserByIDBadRequest{}
}

/*DeleteUserByIDBadRequest handles this case with default header values.

Invalid ID supplied
*/
type DeleteUserByIDBadRequest struct {
}

func (o *DeleteUserByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUserByIdBadRequest ", 400)
}

func (o *DeleteUserByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteUserByIDNotFound creates a DeleteUserByIDNotFound with default headers values
func NewDeleteUserByIDNotFound() *DeleteUserByIDNotFound {
	return &DeleteUserByIDNotFound{}
}

/*DeleteUserByIDNotFound handles this case with default header values.

User not found
*/
type DeleteUserByIDNotFound struct {
}

func (o *DeleteUserByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /users/{id}][%d] deleteUserByIdNotFound ", 404)
}

func (o *DeleteUserByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
