// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteRoleByIDOKCode is the HTTP code returned for type DeleteRoleByIDOK
const DeleteRoleByIDOKCode int = 200

/*DeleteRoleByIDOK successful operation

swagger:response deleteRoleByIdOK
*/
type DeleteRoleByIDOK struct {
}

// NewDeleteRoleByIDOK creates DeleteRoleByIDOK with default headers values
func NewDeleteRoleByIDOK() *DeleteRoleByIDOK {

	return &DeleteRoleByIDOK{}
}

// WriteResponse to the client
func (o *DeleteRoleByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteRoleByIDBadRequestCode is the HTTP code returned for type DeleteRoleByIDBadRequest
const DeleteRoleByIDBadRequestCode int = 400

/*DeleteRoleByIDBadRequest Invalid ID supplied

swagger:response deleteRoleByIdBadRequest
*/
type DeleteRoleByIDBadRequest struct {
}

// NewDeleteRoleByIDBadRequest creates DeleteRoleByIDBadRequest with default headers values
func NewDeleteRoleByIDBadRequest() *DeleteRoleByIDBadRequest {

	return &DeleteRoleByIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteRoleByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteRoleByIDNotFoundCode is the HTTP code returned for type DeleteRoleByIDNotFound
const DeleteRoleByIDNotFoundCode int = 404

/*DeleteRoleByIDNotFound Role not found

swagger:response deleteRoleByIdNotFound
*/
type DeleteRoleByIDNotFound struct {
}

// NewDeleteRoleByIDNotFound creates DeleteRoleByIDNotFound with default headers values
func NewDeleteRoleByIDNotFound() *DeleteRoleByIDNotFound {

	return &DeleteRoleByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteRoleByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
