// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "models"
)

// GetAllRolesOKCode is the HTTP code returned for type GetAllRolesOK
const GetAllRolesOKCode int = 200

/*GetAllRolesOK successful operation

swagger:response getAllRolesOK
*/
type GetAllRolesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Role `json:"body,omitempty"`
}

// NewGetAllRolesOK creates GetAllRolesOK with default headers values
func NewGetAllRolesOK() *GetAllRolesOK {

	return &GetAllRolesOK{}
}

// WithPayload adds the payload to the get all roles o k response
func (o *GetAllRolesOK) WithPayload(payload []*models.Role) *GetAllRolesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all roles o k response
func (o *GetAllRolesOK) SetPayload(payload []*models.Role) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllRolesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.Role, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
