// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetAllRolesParams creates a new GetAllRolesParams object
// no default values defined in spec.
func NewGetAllRolesParams() GetAllRolesParams {

	return GetAllRolesParams{}
}

// GetAllRolesParams contains all the bound params for the get all roles operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAllRoles
type GetAllRolesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAllRolesParams() beforehand.
func (o *GetAllRolesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
