// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAllRolesParams creates a new GetAllRolesParams object
// with the default values initialized.
func NewGetAllRolesParams() *GetAllRolesParams {

	return &GetAllRolesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAllRolesParamsWithTimeout creates a new GetAllRolesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAllRolesParamsWithTimeout(timeout time.Duration) *GetAllRolesParams {

	return &GetAllRolesParams{

		timeout: timeout,
	}
}

// NewGetAllRolesParamsWithContext creates a new GetAllRolesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAllRolesParamsWithContext(ctx context.Context) *GetAllRolesParams {

	return &GetAllRolesParams{

		Context: ctx,
	}
}

// NewGetAllRolesParamsWithHTTPClient creates a new GetAllRolesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAllRolesParamsWithHTTPClient(client *http.Client) *GetAllRolesParams {

	return &GetAllRolesParams{
		HTTPClient: client,
	}
}

/*GetAllRolesParams contains all the parameters to send to the API endpoint
for the get all roles operation typically these are written to a http.Request
*/
type GetAllRolesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get all roles params
func (o *GetAllRolesParams) WithTimeout(timeout time.Duration) *GetAllRolesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get all roles params
func (o *GetAllRolesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get all roles params
func (o *GetAllRolesParams) WithContext(ctx context.Context) *GetAllRolesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get all roles params
func (o *GetAllRolesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get all roles params
func (o *GetAllRolesParams) WithHTTPClient(client *http.Client) *GetAllRolesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get all roles params
func (o *GetAllRolesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAllRolesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
