app:
  name: WebApp
  
logging:
  output: stderr  # stdout, stderr
  format: text    # text, json
  level: debug    # info, error, warn, debug, etc..

server:
  port: 8080
  writeTimeout: 30
  readTimeout: 15
  idleTimeout: 60

repository:
  roles:
    provider: mongodb
    mongodb:
      database: roles
      url: mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test
  users:
    provider: mongodb
    mongodb:
      database: users
      url: mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test


