// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "models"
)

// GetAllUsersOKCode is the HTTP code returned for type GetAllUsersOK
const GetAllUsersOKCode int = 200

/*GetAllUsersOK successful operation

swagger:response getAllUsersOK
*/
type GetAllUsersOK struct {

	/*
	  In: Body
	*/
	Payload []*models.User `json:"body,omitempty"`
}

// NewGetAllUsersOK creates GetAllUsersOK with default headers values
func NewGetAllUsersOK() *GetAllUsersOK {

	return &GetAllUsersOK{}
}

// WithPayload adds the payload to the get all users o k response
func (o *GetAllUsersOK) WithPayload(payload []*models.User) *GetAllUsersOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all users o k response
func (o *GetAllUsersOK) SetPayload(payload []*models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllUsersOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make([]*models.User, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
