// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi WebApp
This is a sample WebApp go server

Terms Of Service:

http://swagger.io/terms/


    Schemes:
      http
    Host: localhost:8080
    BasePath: /
    Version: 1.0.0
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
    Contact: <jsa4000@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
