version: "3.5"
services:

  mongo:
    image: 3.4.19-jessie
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
    - webapp-network

  redis:
    image: redis:5.0.3-alpine
    environment:
      REDIS_PASSWORD: root
    networks:
      - webapp-network

  webapp-go:
   image: webapp-go
   ports:
   - "8080:8080"
   environment:
     REPOSITORY_MONGODB_URL: mongodb://root:root@mongo:27017/admin
   volumes:
   - //d/DEVELOPMENT/Github/Getting-Started-Golang/src/webapp/config.docker.yaml:/config.yaml
   networks: 
    - webapp-network

networks:
  webapp-network:
    name: webapp-network