version: "3.5"
services:

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks: 
    - webapp-network

  redis:
    image: redis:5.0.3-alpine
    command: ["redis-server", "--requirepass", "root"]
    ports:
      - "6379:6379"
    networks:
      - webapp-network

networks:
  webapp-network:
    name: webapp-network