// Code generated by go-swagger; DO NOT EDIT.

package roles

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteRoleByIDReader is a Reader for the DeleteRoleByID structure.
type DeleteRoleByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteRoleByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteRoleByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewDeleteRoleByIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteRoleByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteRoleByIDOK creates a DeleteRoleByIDOK with default headers values
func NewDeleteRoleByIDOK() *DeleteRoleByIDOK {
	return &DeleteRoleByIDOK{}
}

/*DeleteRoleByIDOK handles this case with default header values.

successful operation
*/
type DeleteRoleByIDOK struct {
}

func (o *DeleteRoleByIDOK) Error() string {
	return fmt.Sprintf("[DELETE /roles/{id}][%d] deleteRoleByIdOK ", 200)
}

func (o *DeleteRoleByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRoleByIDBadRequest creates a DeleteRoleByIDBadRequest with default headers values
func NewDeleteRoleByIDBadRequest() *DeleteRoleByIDBadRequest {
	return &DeleteRoleByIDBadRequest{}
}

/*DeleteRoleByIDBadRequest handles this case with default header values.

Invalid ID supplied
*/
type DeleteRoleByIDBadRequest struct {
}

func (o *DeleteRoleByIDBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /roles/{id}][%d] deleteRoleByIdBadRequest ", 400)
}

func (o *DeleteRoleByIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteRoleByIDNotFound creates a DeleteRoleByIDNotFound with default headers values
func NewDeleteRoleByIDNotFound() *DeleteRoleByIDNotFound {
	return &DeleteRoleByIDNotFound{}
}

/*DeleteRoleByIDNotFound handles this case with default header values.

Role not found
*/
type DeleteRoleByIDNotFound struct {
}

func (o *DeleteRoleByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /roles/{id}][%d] deleteRoleByIdNotFound ", 404)
}

func (o *DeleteRoleByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
