// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// CreateUserMethodNotAllowedCode is the HTTP code returned for type CreateUserMethodNotAllowed
const CreateUserMethodNotAllowedCode int = 405

/*CreateUserMethodNotAllowed Invalid input

swagger:response createUserMethodNotAllowed
*/
type CreateUserMethodNotAllowed struct {
}

// NewCreateUserMethodNotAllowed creates CreateUserMethodNotAllowed with default headers values
func NewCreateUserMethodNotAllowed() *CreateUserMethodNotAllowed {

	return &CreateUserMethodNotAllowed{}
}

// WriteResponse to the client
func (o *CreateUserMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(405)
}

// CreateUserInternalServerErrorCode is the HTTP code returned for type CreateUserInternalServerError
const CreateUserInternalServerErrorCode int = 500

/*CreateUserInternalServerError Internal Server Error

swagger:response createUserInternalServerError
*/
type CreateUserInternalServerError struct {
}

// NewCreateUserInternalServerError creates CreateUserInternalServerError with default headers values
func NewCreateUserInternalServerError() *CreateUserInternalServerError {

	return &CreateUserInternalServerError{}
}

// WriteResponse to the client
func (o *CreateUserInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
