// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteUserByIDOKCode is the HTTP code returned for type DeleteUserByIDOK
const DeleteUserByIDOKCode int = 200

/*DeleteUserByIDOK successful operation

swagger:response deleteUserByIdOK
*/
type DeleteUserByIDOK struct {
}

// NewDeleteUserByIDOK creates DeleteUserByIDOK with default headers values
func NewDeleteUserByIDOK() *DeleteUserByIDOK {

	return &DeleteUserByIDOK{}
}

// WriteResponse to the client
func (o *DeleteUserByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteUserByIDBadRequestCode is the HTTP code returned for type DeleteUserByIDBadRequest
const DeleteUserByIDBadRequestCode int = 400

/*DeleteUserByIDBadRequest Invalid ID supplied

swagger:response deleteUserByIdBadRequest
*/
type DeleteUserByIDBadRequest struct {
}

// NewDeleteUserByIDBadRequest creates DeleteUserByIDBadRequest with default headers values
func NewDeleteUserByIDBadRequest() *DeleteUserByIDBadRequest {

	return &DeleteUserByIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteUserByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteUserByIDNotFoundCode is the HTTP code returned for type DeleteUserByIDNotFound
const DeleteUserByIDNotFoundCode int = 404

/*DeleteUserByIDNotFound User not found

swagger:response deleteUserByIdNotFound
*/
type DeleteUserByIDNotFound struct {
}

// NewDeleteUserByIDNotFound creates DeleteUserByIDNotFound with default headers values
func NewDeleteUserByIDNotFound() *DeleteUserByIDNotFound {

	return &DeleteUserByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteUserByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
