// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteUserByIDParams creates a new DeleteUserByIDParams object
// with the default values initialized.
func NewDeleteUserByIDParams() *DeleteUserByIDParams {
	var ()
	return &DeleteUserByIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUserByIDParamsWithTimeout creates a new DeleteUserByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUserByIDParamsWithTimeout(timeout time.Duration) *DeleteUserByIDParams {
	var ()
	return &DeleteUserByIDParams{

		timeout: timeout,
	}
}

// NewDeleteUserByIDParamsWithContext creates a new DeleteUserByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUserByIDParamsWithContext(ctx context.Context) *DeleteUserByIDParams {
	var ()
	return &DeleteUserByIDParams{

		Context: ctx,
	}
}

// NewDeleteUserByIDParamsWithHTTPClient creates a new DeleteUserByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUserByIDParamsWithHTTPClient(client *http.Client) *DeleteUserByIDParams {
	var ()
	return &DeleteUserByIDParams{
		HTTPClient: client,
	}
}

/*DeleteUserByIDParams contains all the parameters to send to the API endpoint
for the delete user by Id operation typically these are written to a http.Request
*/
type DeleteUserByIDParams struct {

	/*ID
	  ID of user to delete

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete user by Id params
func (o *DeleteUserByIDParams) WithTimeout(timeout time.Duration) *DeleteUserByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete user by Id params
func (o *DeleteUserByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete user by Id params
func (o *DeleteUserByIDParams) WithContext(ctx context.Context) *DeleteUserByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete user by Id params
func (o *DeleteUserByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete user by Id params
func (o *DeleteUserByIDParams) WithHTTPClient(client *http.Client) *DeleteUserByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete user by Id params
func (o *DeleteUserByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete user by Id params
func (o *DeleteUserByIDParams) WithID(id string) *DeleteUserByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete user by Id params
func (o *DeleteUserByIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUserByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
